# Import Session from SQLAlchemy.
# A Session is used to communicate with the database.
# It lets us create, read, update, and delete data.
from sqlalchemy.orm import Session

# Import the Post SQLAlchemy model.
# This represents the "posts" table in the database.
from app.models.post import Post

# Import the Pydantic schema used for validating incoming request data.
# This ensures the client sends the correct fields (title and content).
from app.schemas.post import PostCreate


# Function to create a new post in the database.
#
# Parameters:
# db   -> Active database session.
# post -> Validated request body (PostCreate schema).
def create_post(db: Session, post: PostCreate):

    # Convert the Pydantic object into a dictionary,
    # then unpack it into the Post model.
    #
    # Example:
    # post.model_dump() returns:
    # {
    #     "title": "Hello",
    #     "content": "World"
    # }
    #
    # The ** operator converts it into:
    #
    # Post(
    #     title="Hello",
    #     content="World"
    # )
    db_post = Post(**post.model_dump())

    # Add the new Post object to the current database session.
    # At this point, it is NOT yet saved to the database.
    db.add(db_post)

    # Save (commit) all pending changes to the database.
    # This executes the INSERT SQL query.
    db.commit()

    # Refresh the object with the latest data from the database.
    #
    # This updates fields automatically generated by the database,
    # such as:
    # - id
    # - created_at
    db.refresh(db_post)

    # Return the newly created post.
    return db_post


# Function to retrieve all posts from the database.
#
# Parameter:
# db -> Active database session.
def get_posts(db: Session):

    # Query the Post table and return every row.
    #
    # Equivalent SQL:
    #
    # SELECT * FROM posts;
    return db.query(Post).all()